# data extraction
dataset_dir: ../data/datasets
train_size: 10
test_size: 3
pin_mem: True
batch_size: 1
num_workers: 2

# network hyperparameters
epochs: 20
infsteps: 100
infrates: [.1, .1, .1]
network_size: [784, 784, 625]
learning_rate: .05
act_func: sigmoid
per_seq_repeat: 1

# network architecture: FcDHPC,RfDHPC_cm
architecture: RfDHPC_cm
rf_sizes: [3, 3, 5]