# data extraction
dataset_dir: ../data/datasets
# MNIST, fashionMNIST
dataset_type: fashionMNIST
train_size: 30
test_size: 5
pin_mem: True
batch_size: 1
num_workers: 2
padding_size: 5

# network hyperparameters
epochs: 40
infsteps: 100
infrates: [.01, .01, .01, .01]
network_size: [1444, 2000, 100]
learning_rate: .001
act_func: sigmoid  # relu, sigmoid
per_seq_repeat: 1

# network architecture: FcDHPC,RfDHPC_cm
architecture: FcDHPC
rf_sizes: [5, 9, 15]

# used to generate morphing dataset
frame_per_sequence: 5
seq_train: True  # whether to train network on seq, if true load dataloader of seqences, and log representation at end of sequences during training for classification
reset_per_frame: True
morph_type: spin
reg_strength: .1
reg_type: none
infstep_before_update: 50
act_norm: False
norm_constant: .0001