# data extraction
dataset_dir: ../data/datasets
train_size: 10
test_size: 3
pin_mem: True
batch_size: 1
num_workers: 2

# network hyperparameters
epochs: 10
infsteps: 100
infrates: [.1, .07, .05]
network_size: [784, 1000, 50]
learning_rate: .05
act_func: sigmoid
per_seq_repeat: 1