# data extraction
dataset_dir: ../data/datasets
# MNIST, fashionMNIST
dataset_type: fashionMNIST
train_size: 10
test_size: 3
pin_mem: True
batch_size: 50
num_workers: 2
padding_size: 5

# network hyperparameters
epochs: 50
infsteps: 100
infrates: [.1, .1, .1]
network_size: [1444, 2000, 50]
learning_rate: .005
act_func: sigmoid  # relu, sigmoid
per_seq_repeat: 1

# network architecture: FcDHPC,RfDHPC_cm
architecture: FcDHPC
rf_sizes: [5, 9, 15]

# used to generate morphing dataset
frame_per_sequence: 5
morph_type: spin